### ISSUE TITLE
Rails 6 encounters "type "ksuid" does not exist"

### ISSUE THREAD

**Issue by rememberlenny** [michaelherold/ksuid-ruby#21]
Hey!

Not sure what information you need, but when trying to add the KSUID type in an existing modal, I get the following error:

```
rake db:migrate
/Users/XXXXXX/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/associations.rb:1370: warning: The called method `has_many' is defined here
== 20201215203500 AddKsuidToUserProjectDownload: migrating ====================
-- add_column(:user_project_downloads, :unique_id, :ksuid)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedObject: ERROR:  type "ksuid" does not exist
LINE 1: ALTER TABLE "user_project_downloads" ADD "unique_id" ksuid
                                                             ^
/Users/XXXXXX/db/migrate/20201215203500_add_ksuid_to_user_project_download.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedObject: ERROR:  type "ksuid" does not exist
LINE 1: ALTER TABLE "user_project_downloads" ADD "unique_id" ksuid
                                                             ^
/Users/XXXXXX/db/migrate/20201215203500_add_ksuid_to_user_project_download.rb:3:in `change'

Caused by:
PG::UndefinedObject: ERROR:  type "ksuid" does not exist
LINE 1: ALTER TABLE "user_project_downloads" ADD "unique_id" ksuid
                                                             ^
/Users/XXXXXX//db/migrate/20201215203500_add_ksuid_to_user_project_download.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

With a migration that looks like this:
```
class AddKsuidToUserProjectDownload < ActiveRecord::Migration[6.0]
  def change
    add_column :user_project_downloads, :unique_id, :ksuid
  end
end
```

**Comment by bgvo** [comment]
@rememberlenny You probably haven't created the type in your database. You can just open a rails console and run:

```ruby
 ActiveRecord::Base.connection.execute("CREATE DOMAIN ksuid AS TEXT")
```

However, please note that this won't last if you ever reset or drop your database. For those cases, I recommend creating a task to assist on this:

```ruby
Rake::Task["db:create"].enhance do
  # Code run after database is created
  Rake::Task["db:types:create"].invoke
end

namespace :db do
  namespace :types do
    task :create => :environment do
      ActiveRecord::Base.connection.execute("CREATE DOMAIN ksuid AS TEXT")
    end
  end
end
```

**Comment by michaelherold** [comment]
I believe this should be fixed by one of the fixes in #30, specifically https://github.com/michaelherold/ksuid-ruby/commit/0eabe44ced7b1bbc41b804dacf2a9bb4963b766a. Let me know if it doesn't!

**Comment by DataDaoDe** [comment]
I'm still getting the issue `"type "ksuid" does not exist.` in Rails 7, specifically `7.0.8`.

**Comment by michaelherold** [comment]
@DataDaoDe, have you upgraded to `activerecord-ksuid`? Can you share more information about how you have things set up?

**Comment by DataDaoDe** [comment]
@michaelherold. Yes, I'm using the latest `1.0.0` of `activerecord-ksuid`. I just followed the [README](https://github.com/michaelherold/ksuid-ruby/blob/main/activerecord-ksuid/README.md#installation) and that led to the errors.

**Comment by michaelherold** [comment]
Which database are you using?

**Comment by DataDaoDe** [comment]
I'm using ruby `3.2.0` and postgesql `15.3`.

**Comment by michaelherold** [comment]
Are you getting the error when running a migration that uses `create_table`? Or `add_column`?

**Comment by DataDaoDe** [comment]
So I just started an empty rails project this morning and tested it all out. Here's the steps to reproduce all errors.

1. rails new project with ruby 3.2.0 and rails 7.0.8.
2. Add to Gemfile: (also tried w/out 'ksuid' same error)
```
gem 'ksuid'
gem 'activerecord-ksuid', require: 'active_record/ksuid/railtie'
```
3. Run `rails generate model Event my_field_name:ksuid` => creates error.
4. Create a migration file and use `add_column` => creates error.
5. Create a migration file and use `create_table` => does not create error and works as expected.
